/* auto-generated by src/policy.py — Material B; smoothed policy (tol=0.2), f*[T][K] in Hz, 0 = no feasible point */
#define POLICY_N_T 4
#define POLICY_N_K 7
static const float POLICY_T_C[POLICY_N_T] = {25, 50, 70, 90};
static const float POLICY_K_THZ[POLICY_N_K] = {3000, 5000, 8000, 12000, 20000, 30000, 40000};
static const unsigned long POLICY_F_STAR_HZ[POLICY_N_T][POLICY_N_K] = {
  {127633, 127633, 127633, 138009, 196183, 248026, 366625},
  {118037, 118037, 118037, 143510, 204002, 248026, 301550},
  {122741, 122741, 122741, 155177, 212132, 257911, 257911},
  {132720, 132720, 138009, 181433, 229378, 268189, 301550},
};
