/* auto-generated by src/policy.py — Material B; smoothed policy (tol=0.2), f*[T][K] in Hz, 0 = no feasible point */
#define POLICY_N_T 4
#define POLICY_N_K 7
static const float POLICY_T_C[POLICY_N_T] = {25, 50, 70, 90};
static const float POLICY_K_THZ[POLICY_N_K] = {3000, 5000, 8000, 12000, 20000, 30000, 40000};
static const unsigned long POLICY_F_STAR_HZ[POLICY_N_T][POLICY_N_K] = {
  {248026, 248026, 248026, 248026, 313568, 313568, 313568},
  {248026, 248026, 248026, 248026, 396431, 313568, 313568},
  {248026, 248026, 248026, 248026, 396431, 501190, 445743},
  {97086, 204002, 204002, 248026, 396431, 313568, 313568},
};
